const Router = require('express')
const router = new Router()
const trainerRouter = require('./trainerRouter')
const gameRouter = require('./gameRouter')
const userRouter = require('./userRouter')
const trainerUserRouter = require('./trainerUserRouter')
const materialRouter = require('./materialRouter')
const statisticRouter = require('./statisticRouter')
const materialUserRouter = require('./materialUserRouter')
const newsRouter = require('./newsRouter')

router.use('/trainer', trainerRouter)
router.use('/game', gameRouter)
router.use('/user', userRouter)
router.use('/trainer_user', trainerUserRouter)
router.use('/material', materialRouter)
router.use('/statistic', statisticRouter)
router.use('/material_user', materialUserRouter)
router.use('/news', newsRouter)

module.exports = router